### ISSUE TITLE
基于TFT_eSPI库使用时需要做的一些调整

### ISSUE THREAD

**Issue by 2827700630** [StarCompute/tftziku#1]
感谢大佬的贡献，我在esp32和TFT_eSPI库的基础上使用了这个中文字库补丁并成功显示中文，希望大佬能直接把它上传到platformio的library上。下面是我使用时发现需要做的一些调整
1. 需要放进platformio工程的文件是src里面的`xfont.cpp`、`xfont.h`和`main.cpp`，data（包括文件夹）和里面的`x.font`
2. 这个补丁同时支持Arduino_GFX和TFT_eSPI库，若是使用TFT_eSPI库，需要在`xfont.h`的第3行将`#define TFT_ESPI`取消注释并注释掉上一行，更改后结果如下：
```
// 在这里注释选择使用的库,在80行选择方向，在`xfont.cpp`35行选择方向
// #define ARDUINO_GFX
#define TFT_ESPI
```
3. 屏幕默认顺时针旋转90度显示，若是选择正常显示要在`xfont.h`第80行将`TFT_HEIGHT`和`TFT_WIDTH`换位置，更改后结果如下：
```
#elif defined(TFT_ESPI)
    int screenHeight = TFT_HEIGHT;
    int screenWidth = TFT_WIDTH;
#endif
```
并在`xfont.cpp`将第35行注释掉`// tft.setRotation(1);//顺时针旋转90度显示`
4.若是使用TFT_eSPI库，颜色需由`GREEN`改为`TFT_GREEN`

如果作者大佬有时间的话，可以尝试使用文泉驿点阵字字体

**Comment by StarCompute** [comment]
感谢你的使用，虽然说有些曲折但是你成功显示了中文，我抽空看看如何可以把项目放到platformio的library和arduino的项目中去；
其实如果你使用arduino_gfx估计基本就不会有任何调整的；现在默认支持的是arduino_gfx,所以使用tft_espi就必须注释掉那个define和反向注释
其三，屏幕旋转和相关的设置看个人习惯，我自己是打倒查看的，我可以去加入注释和提醒；
第四点你说的没错，其实我之前也注意到这个问题，只是没有测试，以为兼容了，为了省几行代码；
第五，你可以使用项目自带的那个getxxxx.py自行创建对应的点阵字库，只需要把simsun.xxx改成相应的文件名就好了；

感谢你的使用。

**Comment by StarCompute** [comment]
1,我检查了一下，对于使用tft,我的代码是使用的是tft_green
2,在readme中补充了一些说明。

**Comment by StarCompute** [comment]
再多说几句，推荐使用arduino_gfx,因为tft_espi的那个配置相对不友好，两个驱动的编译后的内存和flash占用我都对比过，相差不大可以忽略；但是arduino_gfx其实又支持ssd1106这种，所以推荐arduino_gfx.

**Comment by 2246411954** [comment]
你好，就是我按照你的教程，在platformio中用TFT_eSPI库上显示，我用的ST7789驱动的tft屏幕，但是烧录进去就屏幕会一直闪，然后串口一直打印下面的信息
ELF file SHA256: 2a8ce709ac764f74

Rebooting...
ets Jul 29 2019 12:21:46

rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1184
load:0x40078000,len:13232
load:0x40080400,len:3028
entry 0x400805e4
Init.
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.

Core  1 register dump:
PC      : 0x400d50f0  PS      : 0x00060e30  A0      : 0x800d5164  A1      : 0x3ffb2140  
A2      : 0x3ffb8a28  A3      : 0x3f4001c1  A4      : 0x00000000  A5      : 0x00000000  
A6      : 0x00000000  A7      : 0x00000000  A8      : 0x800d50ea  A9      : 0xa644475d  
A10     : 0x00000070  A11     : 0x00000070  A12     : 0x00000000  A13     : 0x00000000  
A14     : 0x3ffb7e48  A15     : 0x00000000  SAR     : 0x00000007  EXCCAUSE: 0x0000001c  
EXCVADDR: 0xa6444765  LBEG    : 0x4008430d  LEND    : 0x40084315  LCOUNT  : 0x00000027  


Backtrace: 0x400d50ed:0x3ffb2140 0x400d5161:0x3ffb2170 0x400d5509:0x3ffb21c0 0x400d22a2:0x3ffb21e0 0x400d2821:0x3ffb2220 0x400d1b5a:0x3ffb2240 0x400d762e:0x3ffb2290

**Comment by 2827700630** [comment]
@2246411954 

结合串口信息和屏幕一直闪的问题，我觉得是程序冲突导致了单片机不断重启。请说明你用的是ESP32还是ESP8266或者是其它型号的单片机。在使用这个TFT汉字字库之前，应该先正确配置TFT_eSPI库中的setup.h（路径如下图）
![image](https://github.com/StarCompute/tftziku/assets/60726378/37c67c1e-4fd9-468e-bb16-4eaab0a735f3)
以适配你的单片机。要在setup.h中选择正确的屏幕驱动型号、单片机型号和引脚。具体教程可以看这个视频【零基础专用ESP32点亮TFT，从接线、环境配置到代码说明，全都有】 https://www.bilibili.com/video/BV1jh411c7mN/?share_source=copy_web&vd_source=c91c35fde3c46c7e7f8e829ecd5674f9
这些配置完，在屏幕上显示一个helloworld或者移植一个TFT_eSPI库的示例程序，确保屏幕能正常显示，然后再移植中文字库。希望这个能帮到你

**Comment by 2246411954** [comment]
感谢大佬回复，对的，我用的是esp32，模组是esp32-wroom-32e，那个TFT_eSPI文件我配置过了，屏幕也能正常显示。然后我用esp32-s3也试过，也是同样的情况，就很奇怪。
![A%W91M6H{4B5``NEE0~0)XF](https://github.com/StarCompute/tftziku/assets/168109567/2aab3587-5b31-4226-bd2e-1a61ed21b182)
![MVIMG_20240425_235602](https://github.com/StarCompute/tftziku/assets/168109567/5864d245-c0dc-4087-878f-c6b18d9d4e77)
我感觉这个方案真是我能找到最好的esp32显示全部中文的方法，我之后试试用arduino_gfx看有没有用

**Comment by 2827700630** [comment]
@2246411954 
使用这个字库需要使用littlefs文件系统。正常能显示，但是中文字库没有显示，所以我推断你可能没有使用littlefs文件系统。它的使用方法可以看我写的帖子【基于ESP32的台式电脑远程开机卡 - 嘉立创EDA开源硬件平台】https://oshwhub.com/myhym/yuan-cheng-kai-ji-ka-copy_2024-03-06_15-46-46?_refluxos=a10 之中的2.7-littlefs文件系统部分。使用littlefs后如果仍然无法显示，可以与我联系。你尝试的这两种单片机我手里也有。不过我明天要考试了，回复可能比较慢

**Comment by LiuDuanWw** [comment]
我和上一楼的问题一模一样。 esp32 wroom 32d的模组 st7789的屏 tft_espi正常显示 配置也没问题 运行实例程序也没问题

> `  _xFont->DrawChineseEx(10, 10, "业精于勤荒于嬉戏，行成于思毁于随。业精于勤荒于嬉戏，行成于思毁于随。业精于勤荒于嬉戏，行成于思毁于随。业精于勤荒于嬉戏，行成于思毁于随。", c);
  //_xFont->DrawChineseEx(0, 10, "业精于勤荒于嬉戏，\n行成于思毁于随。\r\n业精于勤荒于嬉戏，\n行成于思毁于随。\r\n业精于勤荒于嬉戏，\n行成于思毁于随。\r\n业精于勤荒于嬉戏，行成于思毁于随。", c);`  注释上面一行用下面一行就闪屏不正常显示 或者稍微改一下显示内容都会这样的情况 字库是生成的全字库   不知道楼上的解决没有

**Comment by LiuDuanWw** [comment]
> 我和上一楼的问题一模一样。 esp32 wroom 32d的模组 st7789的屏 tft_espi正常显示 配置也没问题 运行实例程序也没问题
> 
> > `  _xFont->DrawChineseEx(10, 10, "业精于勤荒于嬉戏，行成于思毁于随。业精于勤荒于嬉戏，行成于思毁于随。业精于勤荒于嬉戏，行成于思毁于随。业精于勤荒于嬉戏，行成于思毁于随。", c);   //_xFont->DrawChineseEx(0, 10, "业精于勤荒于嬉戏，\n行成于思毁于随。\r\n业精于勤荒于嬉戏，\n行成于思毁于随。\r\n业精于勤荒于嬉戏，\n行成于思毁于随。\r\n业精于勤荒于嬉戏，行成于思毁于随。", c);`  注释上面一行用下面一行就闪屏不正常显示 或者稍微改一下显示内容都会这样的情况 字库是生成的全字库   不知道楼上的解决没有

x.font也是按照作者的方法手动上传的
