### ISSUE TITLE
使用 ARDUINO_GFX 程序编译出错。

### ISSUE THREAD

**Issue by changxinchang** [StarCompute/tftziku#10]
显示这个错误。fatal error: esp_memory_utils.h: No such file or directory
 #include <esp_memory_utils.h>
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
已经安装了ESP32_Display_panel。

**Comment by StarCompute** [comment]
我今天也发觉了这个问题，之前没有问题，估计要么IDF的问题，要么是arduino_gfx问题，你可以暂时不适用gfx就可以解决了。

**Comment by StarCompute** [comment]
这个问题确认了是arduino_gfx的问题，官方从1.4.7升级到1.4.8出现了问题，目前已经更新到了1.4.9. 需要手动更新或者等其他各种同步。
https://github.com/moononournation/Arduino_GFX/issues/534

**Comment by changxinchang** [comment]
现在编译不报错了，但是显示是白屏

**Comment by changxinchang** [comment]
TFT_ESPI编译没问题，arduino_gfx 1.4.9编译没问题，上传到ESP32C3直接白屏。

**Comment by StarCompute** [comment]
已经按照faq.rst中的各种问题检查过了？
怀疑你字库没有上传！

**Comment by StarCompute** [comment]
如果串口没有提示字库问题，请独立验证tft 驱动是否工作正常

**Comment by changxinchang** [comment]
串口有输出   使用arduino_gfx是白屏，TFT_ESPI模式正常。
TFT初始化耗时:0.354000 秒.
37715
     字符总数:37715 
     装载字符集耗时:0.020000 秒.
对象初始化耗时：0.374 
     屏幕输出汉字耗时:0.058000 秒.
     屏幕输出汉字耗时:0.043000 秒.
销毁后剩余内: 256.234 k

**Comment by changxinchang** [comment]
经过多次重启开发板，发现这个故障，怀疑白屏和这个有关。
TFT初始化耗时:0.354000 秒.
E (484) esp_littlefs: ./components/esp_littlefs/src/littlefs/lfs.c:1347:error: Corrupted dir pair at {0x0, 0x1}

E (486) esp_littlefs: mount failed,  (-84)
E (490) esp_littlefs: Failed to initialize LittleFS
littleFS 文件系统初始化失败,请检查相关配置。
     装载字符集耗时:0.022000 秒.
对象初始化耗时：0.376 
E (529) esp_littlefs: ./components/esp_littlefs/src/littlefs/lfs.c:1347:error: Corrupted dir pair at {0x0, 0x1}

E (530) esp_littlefs: mount failed,  (-84)
E (532) esp_littlefs: Failed to initialize LittleFS
littleFS 文件系统初始化失败,请检相关配置。
字库初始化失败
E (548) esp_littlefs: ./components/esp_littlefs/src/littlefs/lfs.c:1347:error: Corrupted dir pair at {0x0, 0x1}

E (554) esp_littlefs: mount failed,  (-84)
E (558) esp_littlefs: Failed to initialize LittleFS
littleFS 文件系统初始化失败,请检查相关配置。
字库初始化失败
销毁后剩余内存: 299.777 k

**Comment by changxinchang** [comment]
相同的代码，使用arduino_gfx 白屏，改用TFT_ESPI 可以正常显示。使用的是 arduino_gfx 1.4.9

**Comment by StarCompute** [comment]
你的文件系统工作不正常，字库没有上传成功。
faq 里面专门有一节是讲如何上传字库的。

**Comment by changxinchang** [comment]
arduino_gfx还是白屏，esp32的版本是 2.0.14 更新到3.0.2还是白屏。
下面是两个模式串口输出的信息。
Arduino_GFX mode     TFT初始化耗时:0.354000 秒.
37715
     字符总数:37715 
     装载字符集耗时:0.020000 .
对象初始化耗时：0.374 
     屏幕输出汉字耗时:0.058000 秒.
     屏幕输出汉字耗时:0.057000 秒.
销毁后剩余内存: 256.234 k 

ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x1 (POWERON),boot:0xc (SPI_FAST_FLASH_BOOT)
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd5810,len:0x38c
load:0x403cc710,len:0x6a0
load:0x403ce710,len:0x25f4
entry 0x403cc710
Init.

     TFT初始化耗时:0.949000 秒.
37715
     字符总数:37715 
     装载字符集耗时:0.020000 .
对象初始化耗时：0.969 
     屏幕输出汉字耗时:0.069000 秒.
     屏幕输出汉字耗时:0.068000 秒.
销毁后剩余内存: 258.195 k

**Comment by StarCompute** [comment]
gfx 白屏基本就是你tft屏幕配置有问题。
不使用字库确认你的配置可以成功显示。

**Comment by changxinchang** [comment]
还在查配置的问题，暂时还没找到故障。

**Comment by StarCompute** [comment]
tft 你可以使用默认gpio配置。

**Comment by changxinchang** [comment]
Arduino_DataBus *bus = new Arduino_ESP32SPI(6,7,8,10);
通过这个代码改了引脚，可以使用了。但是屏幕有偏移，原本要在0，0显示的文字跑到屏幕的最下面。

**Comment by StarCompute** [comment]
我大概知道原因，建议你再看一遍faq

**Comment by changxinchang** [comment]
大脑有点死机，没转过来。还是没找到哪里出问题了。显示的文字有问题，图片也有问题。图片完全是错的。搞的头有点大。

**Comment by StarCompute** [comment]
xfont 设置了画布旋转，你检查一下，在xfont里面有设置了旋转，你看看是不是这个原因。

**Comment by changxinchang** [comment]
经过你的提示，重要正常了。谢谢了。
