### ISSUE TITLE
求支持GxEPD2墨水屏显示库

### ISSUE THREAD

**Issue by 217heidai** [StarCompute/tftziku#11]
求支持[GxEPD2](https://github.com/ZinggJM/GxEPD2)墨水屏显示库

**Comment by StarCompute** [comment]
其实你可以自己稍微修改一下就可以引入 GxEPD2了：
1，初始化对象；
2，调用驱动的drawPix方法；
3，替换涉及到drawPix方法的地方
这就大功告成了。
