### ISSUE TITLE
谢谢兄弟，正在用这个自己写SSD1306驱动ing

### ISSUE THREAD

**Issue by LunaticLegacy** [StarCompute/tftziku#12]
问一下，这个……（我会署名的）

**Comment by StarCompute** [comment]
???

**Comment by LunaticLegacy** [comment]
> ???

就是，我想在我的SSD1306驱动中，将你的字库文件加进去。（虽然我也是个单片机初学者）

**Comment by StarCompute** [comment]
1，项目引用的arduino_gfx好像带ssd1306驱动；
2，如果你要使用第三方驱动，xfont有个不初始化tft的方法供调用，请参考示例代码；
