### ISSUE TITLE
littlefs出错 找不到字库文件

### ISSUE THREAD

**Issue by xcjk-tofuture** [StarCompute/tftziku#2]
E (196783) esp_littlefs: ./components/esp_littlefs/src/littlefs/lfs.c:1347:error: Corrupted dir pair at {0x0, 0x1}

E (196787) esp_littlefs: mount failed,  (-84)
E (196791) esp_littlefs: Failed to initialize LittleFS
[196987][E][LittleFS.cpp:95] begin(): Mounting LittleFS failed! Error: -1
[196993][E][vfs_api.cpp:24] open(): File system is not mounted
找不到字库文件。
字库初始化失败

安装步骤用python文件传输了font字体进去 并在platform.ini添加了littleFS的支持 依旧会报此错误

**Comment by StarCompute** [comment]
littlefs 的引用估计需要你自己解决，在platform.ini中加上配置或者添加这个库进去，因为littlefs 有的时候真的是莫名奇妙。
python 上传文件没有报错对吧。
你可以试试platformio 把esp32 flash全部清除后试试。

**Comment by StarCompute** [comment]
从代码提示上来看还是little fs没有工作正常，否则不会有：
File system is not mounted 
这种提示。

**Comment by StarCompute** [comment]
添加了littlefs的支持后，有的时候最好要清除一下之前的各种编译文件。
