### ISSUE TITLE
有几个问题，python的那个PIL库停用了下不了，然后更换替代库后直接就报错了

### ISSUE THREAD

**Issue by justdomyself** [StarCompute/tftziku#3]
1、PIL 停止维护，下载不了。网上建议  使用Pillow替换。

2、SyntaxError: Non-UTF-8 code starting with '\xef' in file F:\Python\python_getUnicode\main.py on line 20, but no encoding declared;  

也就是这一行报错;
FONT_GB3212 = '　、。・ˉˇ¨〃々―～‖…‘’“”〔〕〈〉《》「 

你弄好的全字库文件能否提供上

3、我用的esp32s3模块，板子是自己画的，那么上传字库的时候，开发板型号怎么选？

**Comment by StarCompute** [comment]
1，PIL不能用了吗？哈哈哈
2，我在本地测试是可以正常运行的，部分unicode编码是有问题，但是都被我try catch处理掉了；
3，已经新上传了很多字库，详细你可以阅读faq.rst这个文件。
4，S3 这个问题理论上不该我来回答，哈哈哈。这个一般是没有任何问题的，关键在于你的flash空间大小和你如何使用的，也就是说如果你不使用特别大号的字体，你可以保持你的platformio配置。

enjoy

**Comment by StarCompute** [comment]
PIL 的问题 请安装  Pillow ，其他相关请阅读faq.rst文件

**Comment by justdomyself** [comment]
> PIL 的问题 请安装 Pillow ，其他相关请阅读faq.rst文件

我试过vscode platformio 上，将你提供的字库放在data目录下，是可以正确上传并显示的。 但是如果在Arduino 这个软件上怎么弄呢？

还有个地方我给改了下，构造函数由外部提供Arduino_DataBus *bs, Arduino_GFX *tf， 因为对于用户而言，屏幕控制器和IO管脚是要自己选的：

`
XFont::XFont(Arduino_DataBus *bs, Arduino_GFX *tf)
{
    this->bus  = bs;
    this->tft = tf;
    InitTFT();
}

class XFont
{

public:
     XFont() ;

#ifdef ARDUINO_GFX
    XFont(Arduino_DataBus *bs, Arduino_GFX *tf);
    Arduino_DataBus *bus;// = create_default_Arduino_DataBus();
    Arduino_GFX *tft;// = new Arduino_ST7735(bus);
    #define GFX_BL DF_GFX_BL
`

然后调用的时候：
Arduino_DataBus *bus = new Arduino_ESP32SPI(LCD_DC /* DC */, LCD_CS /* CS */, LCD_SCK /* SCK */, LCD_MOSI /* MOSI */, LCD_MISO /* MISO */);
Arduino_ST7789 *gfx = new Arduino_ST7789(bus, LCD_RST /* RST */, 1 /* rotation */, false /* IPS */);
XFont *_xFont;

void setup() {
  // put your setup code here, to run once:

  // 注意，xFont的初始化必须在setup内
  _xFont = new XFont(bus, gfx);
  //_xFont->DrawChinese(0, 0, "业精于勤荒于嬉戏，行成于思毁于随。", RED);

}

这样控制器类型和IO管脚选择都可以在外部配置好后，直接调用你的模块，你的源码不用再改 。

**Comment by StarCompute** [comment]
在arduino 早期版本里面，安装一个插件后就可以同样支持上传data目录到flash中，后来的版本升级后就不行了，再后来好像又听说可以了，没有试过。见谅

管脚那个事情是这样的，理论上GPIO外配最好，但是GPIO外配的过程中反而会因为各种原因产生各种问题，让很多人完成显示是第一步，所以默认设置是最好的，对吧。如果完成了显示再需要做一些修改，其实就比较简单了。
因此，对于tft_espi和arduino_gfx,都没做GPIO在初始化的时候传入，事实上，是可以加一个#ifdifine 来把两个驱动统一拿出来，但是某种角度是增加了复杂度，甚至说现在加了两个tft驱动都是增加了复杂度。

**Comment by StarCompute** [comment]
我重新看了一下你的那个代码调整，你这样驱动对象外置是可以的，刚刚也尝试这么去调整了一下，才发觉要改setup中的内容，而且出现不兼容的混乱可以导致，所以我又没有调解。不过对于驱动的修改问题，我把他补入faq.rst中了。
非常感谢

**Comment by justdomyself** [comment]
还有一个问题，文件系统被频繁打开和关闭，我显示4行汉字需要3.5s。

我改成初始化的时候只打开一次，后面直接用，去掉下面这个：

    if(LittleFS.begin()==false){
         Serial.println("littleFS 文件系统初始化失败,请检查相关配置。");
         return;

     }
     if (LittleFS.exists(fontPath))

4行汉字显示时间减少到0.7s。

**Comment by StarCompute** [comment]
> 还有一个问题，文件系统被频繁打开和关闭，我显示4行汉字需要3.5s。
> 
> 我改成初始化的时候只打开一次，后面直接用，去掉下面这个：
> 
> ```
> if(LittleFS.begin()==false){
>      Serial.println("littleFS 文件系统初始化失败,请检查相关配置。");
>      return;
> 
>  }
>  if (LittleFS.exists(fontPath))
> ```
> 
> 4行汉字显示时间减少到0.7s。

谢谢，我抽空检查一下更新，可能是之前更新了一些方法，导致了一些问题。麻烦把你修改的具体地方告知一下，谢谢。

**Comment by StarCompute** [comment]
非常非常感谢，我大概明白了，之前的数据是统一在那个方法中获取的，只IO一次，后来发觉由于esp32和esp8266的ram大小相差太大就调整了getPixBinStrFromString 这个方法每次只获取一次汉字，所以导致了频繁IO，说实话我自己也不满意这个速度，但是错误的以为是spi本身的drawpix导致的，还折腾了一下。
我抽空处理一下，把file public一下，不过我手里的屏幕又不知道被我放到哪里去了，大哭。

**Comment by StarCompute** [comment]
说一下我的调整思路，File file 放到了 class的public中，在initziku中打开一次，其他方法中都判断file是否存在，然后每次调用file.seek(0)，不知道你是不是这么处理的。
这样调整没有验证过，哈哈哈，因为找屏幕太麻烦了。大哭。
可以看看你的改法，谢谢

**Comment by justdomyself** [comment]
> 非常非常感谢，我大概明白了，之前的数据是统一在那个方法中获取的，只IO一次，后来发觉由于esp32和esp8266的ram大小相差太大就调整了getPixBinStrFromString 这个方法每次只获取一次汉字，所以导致了频繁IO，说实话我自己也不满意这个速度，但是错误的以为是spi本身的drawpix导致的，还折腾了一下。 我抽空处理一下，把file public一下，不过我手里的屏幕又不知道被我放到哪里去了，大哭。

我昨天测了一下屏幕 SPI的速度有40M， 这个速度已经不低了。记得之前刷新整屏幕的图片，好像也不会好几秒。这里还是有很大优化空间的。

**Comment by StarCompute** [comment]
> > 非常非常感谢，我大概明白了，之前的数据是统一在那个方法中获取的，只IO一次，后来发觉由于esp32和esp8266的ram大小相差太大就调整了getPixBinStrFromString 这个方法每次只获取一次汉字，所以导致了频繁IO，说实话我自己也不满意这个速度，但是错误的以为是spi本身的drawpix导致的，还折腾了一下。 我抽空处理一下，把file public一下，不过我手里的屏幕又不知道被我放到哪里去了，大哭。
> 
> 我昨天测了一下屏幕 SPI的速度有40M， 这个速度已经不低了。记得之前刷新整屏幕的图片，好像也不会好几秒。这里还是有很大优化空间的。

基本没有优化空间了，我尝试过优化那个drawpix方法，减少里面的某些方法调用，再进行性能测试，后发觉基本没啥影响。

**Comment by StarCompute** [comment]
目前影响性能的主要在于file的定位读取，这个我已经测试过了。你测的0,7S 某种角度来说是可以接受的，你想啊，tft_espi那个性能是更长的时间。

**Comment by StarCompute** [comment]
我不放心，刚刚找出屏幕测试了一下，显示了“业精于勤荒于嬉戏，行成于思毁于随。业精于勤荒于嬉戏，行成于思毁于随。业精于勤荒于嬉戏，行成于思毁于随。业精于勤荒于嬉戏，行成于思毁于随。” 这么多汉字，12号字体，7行以上，ST7735. esp8266. 对比了一下 file.open那个修改，有差异，但是差异没有特别明显，没有相差2秒以上。 当然这是人工计数。

**Comment by StarCompute** [comment]
我再在测试了一下，上面的汉字显示出来只要0.7x秒，优化file.open其实只是快了0.14s左右。
其他慢在init那个方法中，因为要读取完整的字库编码，不过esp32比esp8266快很多，因为两者的ram空间不同，采取了不同的读取方式，
