### ISSUE TITLE
字库初始化失败

### ISSUE THREAD

**Issue by brosixa** [StarCompute/tftziku#4]
大佬你好，小白有在显示屏上显示中文的需求，看了你的项目，觉得比通常的.h提前为需要的文字创建字库更方便更高效，但是在运行项目中src/main.c实例时，报错说字库初始化失败：如图
`11:50:17.973 -> rst:0x1 (POWERON_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
11:50:17.973 -> configsip: 0, SPIWP:0xee
11:50:17.973 -> clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
11:50:17.973 -> mode:DIO, clock div:1
11:50:17.973 -> load:0x3fff0030,len:1344
11:50:17.973 -> load:0x40078000,len:13964

11:50:17.973 -> load:0x40080400,len:3600

11:50:17.973 -> entry 0x400805f0

11:50:18.127 -> Init.

11:50:18.510 -> 找不到字库文件。

11:50:18.510 -> 找不到字库文件。

11:50:18.510 -> 字库初始化失败`

xfont.h中 `    String fontFilePath = "/x.font";`，路径正确（已经把x.font放到和项目一个文件下了）
查找了一些资料，我又运行了一个更简单的实例

`#include <LittleFS.h>  
#define SPIFFS LittleFS

#define path "./x.font"

void setup() {  
  Serial.begin(115200);  
  if (!LittleFS.begin()) {  
    Serial.println("LittleFS Mount Failed");  
    return;  
  }  
  Serial.println("LittleFS Mounted");  
  // ... 其他初始化代码 ...  

File file = LittleFS.open(path);
if(!file)
  Serial.println("failed to open");
else
  Serial.println("opened");
}

void loop(){}`

结果显示 `failed to open`，也就是说连打开都打开不了
在查资料的过程中，我了解到可能是我LittleFS系统配置没配置好，比如buffer大小之类的，但是也不知道具体在哪里配置，与很多教程提到的PlatformIO.ini是否有关？，
希望得到大佬的解答，谢谢！

**Comment by StarCompute** [comment]
你的字库应该没有上传成功，这个报错。你需要检查platformio的配置，或者查看我的那个faq文件。

**Comment by StarCompute** [comment]
字库是需要上传到flash空间的，不是默认在/data/x.font就可以使用的。 放在data目录是一种上传标准

**Comment by brosixa** [comment]
噢噢原来是这样，了解了。请问是通过运行以下代码上传吗，我找不到我本地的pio.exe文件

`    # import os
    # os.system("cd ..")
    # os.system("move  "+_font_lib_name+" data\\x.font")
    # 请注意检查下面pio.exe 的配置地址和--environment 后esp32dev 应该为你的配置，这个配置就是你platform.ini中的[env:xxx]中这个xxx
    # os.system("C:\\Users\\xuank\\.platformio\\penv\\Scripts\\pio.exe  run --target uploadfs --environment nodemcuv2")`
只有:
![image](https://github.com/StarCompute/tftziku/assets/119747448/544c926c-d56a-46b6-b051-86f2e1346be4)

在找platform.ini时发现了2个不一样的LittleFS库，使用的时候具体用的哪一个呢（就是，是否有一个多余的，第一个是内置的，第二个是我在ide里安装的）？

![image](https://github.com/StarCompute/tftziku/assets/119747448/72737c4b-4493-427f-bbb3-9536277998a8)

![image](https://github.com/StarCompute/tftziku/assets/119747448/4e4ade24-dd7f-4074-b5de-bd75478c536b)
两个的设备都是[env:esp32]

**Comment by StarCompute** [comment]
你需要自行查阅platformio如何上传data目录，很明显你这块的知识缺乏

**Comment by StarCompute** [comment]
https://blog.csdn.net/platform/article/details/139006314
