### ISSUE TITLE
请问下，在同一个位置显示内容不停变化时，怎样解决不同内容叠加显示乱成一团的问题

### ISSUE THREAD

**Issue by justdomyself** [StarCompute/tftziku#5]
比如我要在第一行显示系统的心跳时间，，一开始显示0，  然后是1,2.。。

但是每次显示新的字符前，没有把之前残存的清掉。导致屏幕上不停的叠加绘制，一团糟

用你的中文库显示函数，或者gfx库显示英文，或者tft_espi库都有这个问题。

简单的办法就是每次显示前，把屏幕整个清一次屏，但是这样有个问题，就是闪烁很严重。

不知道你这有没有好的解决方案。

**Comment by brosixa** [comment]
我也是通过刷新屏幕处理的，但是只是局部刷新，用一个tft画布，设置相同颜色背景再push出去，最后删除。不过我的调用频率比较低，暂时没发现频闪的情况

**Comment by justdomyself** [comment]
> 我也是通过刷新屏幕处理的，但是只是局部刷新，用一个tft画布，设置相同颜色背景再push出去，最后删除。不过我的调用频率比较低，暂时没发现频闪的情况

代码能贴出来参考下么，？
还有像这种库应该带有自己先局部清除，然后在绘制的函数接口才对， 要不用户用起来多难受

**Comment by StarCompute** [comment]
> 比如我要在第一行显示系统的心跳时间，，一开始显示0， 然后是1,2.。。
> 
> 但是每次显示新的字符前，没有把之前残存的清掉。导致屏幕上不停的叠加绘制，一团糟
> 
> 用你的中文库显示函数，或者gfx库显示英文，或者tft_espi库都有这个问题。
> 
> 简单的办法就是每次显示前，把屏幕整个清一次屏，但是这样有个问题，就是闪烁很严重。
> 
> 不知道你这有没有好的解决方案。

对于同一个位置的重画，显示不同的内容，会出现像素重叠的问题，这个我早就知道了，也考虑过是否在某个字符显示的时候先对于屏幕相关区域进行清零，但是后来发觉tft的相关驱动自带的drawstring等方法也存在这个问题，处于保持同步，所以在显示区域就没有提前清零
再换个思路，不知道清零用什么底色来清，这是很重要的一环。因为无法获取到你的底色是什么，举例来说你显示10行，每行的底色是无法获取
也是可以提供一个方法在draw上进行重构，手工输入一个底色，但是这样风格的变了。

**Comment by StarCompute** [comment]
> 我也是通过刷新屏幕处理的，但是只是局部刷新，用一个tft画布，设置相同颜色背景再push出去，最后删除。不过我的调用频率比较低，暂时没发现频闪的情况

局部刷新是最OK的方案。

**Comment by brosixa** [comment]
> > 我也是通过刷新屏幕处理的，但是只是局部刷新，用一个tft画布，设置相同颜色背景再push出去，最后删除。不过我的调用频率比较低，暂时没发现频闪的情况
> 
> 代码能贴出来参考下么，？ 还有像这种库应该带有自己先局部清除，然后在绘制的函数接口才对， 要不用户用起来多难受

`extern void printDate(){
          if(!getLocalTime(&timeinfo)){
                   Serial.println("Failed to obtain time!");
           return;
           }
         spr.setColorDepth(8);     // 局部刷新屏幕
         spr.createSprite(60, 20);
         spr.fillSprite(TFT_WHITE);
         spr.pushSprite(10, 60);
         spr.deleteSprite();

         const char *date = formatChineseDate(&timeinfo);
         _xFont->DrawChinese(10, 60, date, TFT_BLACK);
}`

**Comment by StarCompute** [comment]
> 我也是通过刷新屏幕处理的，但是只是局部刷新，用一个tft画布，设置相同颜色背景再push出去，最后删除。不过我的调用频率比较低，暂时没发现频闪的情况

局部刷新是最OK的方案。

> > > 我也是通过刷新屏幕处理的，但是只是局部刷新，用一个tft画布，设置相同颜色背景再push出去，最后删除。不过我的调用频率比较低，暂时没发现频闪的情况
> > 
> > 
> > 代码能贴出来参考下么，？ 还有像这种库应该带有自己先局部清除，然后在绘制的函数接口才对， 要不用户用起来多难受
> 
> `extern void printDate(){ if(!getLocalTime(&timeinfo)){ Serial.println("Failed to obtain time!"); return; } spr.setColorDepth(8); // 局部刷新屏幕 spr.createSprite(60, 20); spr.fillSprite(TFT_WHITE); spr.pushSprite(10, 60); spr.deleteSprite();
> 
> ```
>      const char *date = formatChineseDate(&timeinfo);
>      _xFont->DrawChinese(10, 60, date, TFT_BLACK);
> ```
> 
> }`

你这个有点麻烦，我提供一个backColor的选择吧，这样就比较简单了。

**Comment by StarCompute** [comment]
> > > 我也是通过刷新屏幕处理的，但是只是局部刷新，用一个tft画布，设置相同颜色背景再push出去，最后删除。不过我的调用频率比较低，暂时没发现频闪的情况
> > 
> > 
> > 代码能贴出来参考下么，？ 还有像这种库应该带有自己先局部清除，然后在绘制的函数接口才对， 要不用户用起来多难受
> 
> `extern void printDate(){ if(!getLocalTime(&timeinfo)){ Serial.println("Failed to obtain time!"); return; } spr.setColorDepth(8); // 局部刷新屏幕 spr.createSprite(60, 20); spr.fillSprite(TFT_WHITE); spr.pushSprite(10, 60); spr.deleteSprite();
> 
> ```
>      const char *date = formatChineseDate(&timeinfo);
>      _xFont->DrawChinese(10, 60, date, TFT_BLACK);
> ```
> 
> }`

已经更新到github，加了一个新的方法，可以添加背景色，如果不是重新覆盖某个区域，不建议加背景色。

**Comment by StarCompute** [comment]
> > 我也是通过刷新屏幕处理的，但是只是局部刷新，用一个tft画布，设置相同颜色背景再push出去，最后删除。不过我的调用频率比较低，暂时没发现频闪的情况
> 
> 代码能贴出来参考下么，？ 还有像这种库应该带有自己先局部清除，然后在绘制的函数接口才对， 要不用户用起来多难受


已经更新到github，加了一个新的方法，可以添加背景色，如果不是重新覆盖某个区域，不建议加背景色。

**Comment by StarCompute** [comment]
> > > 我也是通过刷新屏幕处理的，但是只是局部刷新，用一个tft画布，设置相同颜色背景再push出去，最后删除。不过我的调用频率比较低，暂时没发现频闪的情况
> > 
> > 
> > 代码能贴出来参考下么，？ 还有像这种库应该带有自己先局部清除，然后在绘制的函数接口才对， 要不用户用起来多难受
> 
> `extern void printDate(){ if(!getLocalTime(&timeinfo)){ Serial.println("Failed to obtain time!"); return; } spr.setColorDepth(8); // 局部刷新屏幕 spr.createSprite(60, 20); spr.fillSprite(TFT_WHITE); spr.pushSprite(10, 60); spr.deleteSprite();
> 
> ```
>      const char *date = formatChineseDate(&timeinfo);
>      _xFont->DrawChinese(10, 60, date, TFT_BLACK);
> ```
> 
> }`



> > > 我也是通过刷新屏幕处理的，但是只是局部刷新，用一个tft画布，设置相同颜色背景再push出去，最后删除。不过我的调用频率比较低，暂时没发现频闪的情况
> > 
> > 
> > 代码能贴出来参考下么，？ 还有像这种库应该带有自己先局部清除，然后在绘制的函数接口才对， 要不用户用起来多难受
> 
> `extern void printDate(){ if(!getLocalTime(&timeinfo)){ Serial.println("Failed to obtain time!"); return; } spr.setColorDepth(8); // 局部刷新屏幕 spr.createSprite(60, 20); spr.fillSprite(TFT_WHITE); spr.pushSprite(10, 60); spr.deleteSprite();
> 
> ```
>      const char *date = formatChineseDate(&timeinfo);
>      _xFont->DrawChinese(10, 60, date, TFT_BLACK);
> ```
> 
> }`

多说两句，xfont中的tft对象是可以外部调用的，如果没有其他特殊需求，tft对象支持很多功能，没有必要搞sprite这种，你有特殊要求除外。

**Comment by StarCompute** [comment]
在faq.rst中加入了对于屏闪的说明和建议解决方案。

**Comment by justdomyself** [comment]
> > > > 我也是通过刷新屏幕处理的，但是只是局部刷新，用一个tft画布，设置相同颜色背景再push出去，最后删除。不过我的调用频率比较低，暂时没发现频闪的情况
> > > 
> > > 
> > > 代码能贴出来参考下么，？ 还有像这种库应该带有自己先局部清除，然后在绘制的函数接口才对， 要不用户用起来多难受
> > 
> > 
> > `extern void printDate(){ if(!getLocalTime(&timeinfo)){ Serial.println("Failed to obtain time!"); return; } spr.setColorDepth(8); // 局部刷新屏幕 spr.createSprite(60, 20); spr.fillSprite(TFT_WHITE); spr.pushSprite(10, 60); spr.deleteSprite();
> > ```
> >      const char *date = formatChineseDate(&timeinfo);
> >      _xFont->DrawChinese(10, 60, date, TFT_BLACK);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > }`
> 
> 已经更新到github，加了一个新的方法，可以添加背景色，如果不是重新覆盖某个区域，不建议加背景色。

我试了下，tft espi库的Draw_String 库是不会叠加显示的：

 tft.setTextColor(TFT_GREEN, TFT_BLACK);
  memset(buf, ' ', sizeof(buf));
  sprintf(buf,"%.3f A   ", inaCtrl.current/1000.0);
  tft.drawString(buf ,0, 110);


我看了下，他底层的实现：

int16_t TFT_eSPI::drawString(const char *string, int32_t poX, int32_t poY, uint8_t font)

这个函数内部有类似fillRect(poX+xo, poY - glyph_ab * textsize, cwidth, cheight, textbgcolor); 这种操作，

背景色把要绘制区域填充，然后再绘制字符，就不存在叠加显示的问题， 不知道和你的比那个效率更高。


我用上面的测试代码显示电压、电流这些信息没发现闪屏，挺顺畅的。

**Comment by StarCompute** [comment]
> > > > > 我也是通过刷新屏幕处理的，但是只是局部刷新，用一个tft画布，设置相同颜色背景再push出去，最后删除。不过我的调用频率比较低，暂时没发现频闪的情况
> > > > 
> > > > 
> > > > 代码能贴出来参考下么，？ 还有像这种库应该带有自己先局部清除，然后在绘制的函数接口才对， 要不用户用起来多难受
> > > 
> > > 
> > > `extern void printDate(){ if(!getLocalTime(&timeinfo)){ Serial.println("Failed to obtain time!"); return; } spr.setColorDepth(8); // 局部刷新屏幕 spr.createSprite(60, 20); spr.fillSprite(TFT_WHITE); spr.pushSprite(10, 60); spr.deleteSprite();
> > > ```
> > >      const char *date = formatChineseDate(&timeinfo);
> > >      _xFont->DrawChinese(10, 60, date, TFT_BLACK);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > }`
> > 
> > 
> > 已经更新到github，加了一个新的方法，可以添加背景色，如果不是重新覆盖某个区域，不建议加背景色。
> 
> 我试了下，tft espi库的Draw_String 库是不会叠加显示的：
> 
> tft.setTextColor(TFT_GREEN, TFT_BLACK); memset(buf, ' ', sizeof(buf)); sprintf(buf,"%.3f A ", inaCtrl.current/1000.0); tft.drawString(buf ,0, 110);
> 
> 我看了下，他底层的实现：
> 
> int16_t TFT_eSPI::drawString(const char *string, int32_t poX, int32_t poY, uint8_t font)
> 
> 这个函数内部有类似fillRect(poX+xo, poY - glyph_ab * textsize, cwidth, cheight, textbgcolor); 这种操作，
> 
> 背景色把要绘制区域填充，然后再绘制字符，就不存在叠加显示的问题， 不知道和你的比那个效率更高。
> 
> 我用上面的测试代码显示电压、电流这些信息没发现闪屏，挺顺畅的。

你可以试试新的那个方法，加了背景色的drawChineseEx.理论上我这个更快，因为没有采取fillRect，这个等于说多了一倍的屏幕覆写。
不过如果你不是显示中文的话，还是建议你使用驱动自带的显示英文和数字方法，因为它不用读字库。

**Comment by StarCompute** [comment]
之前以为屏闪是因为显示的时间太长或者背景重绘导致的，所以修正了。

输出英文和数字的时候出现的屏闪是因为这些都是半角的内容，但是屏幕是全角输出，出现了部分不停重复覆盖和输出导致的。
已经在loop中测试了数字不停自增，都没有屏闪
