### ISSUE TITLE
在 ESP32-S3带1.9寸屏幕 上使用 Arduino_GFX_Library 乱码

### ISSUE THREAD

**Issue by cokll** [StarCompute/tftziku#8]
![QQ截图20240618000754](https://github.com/StarCompute/tftziku/assets/24391313/b9eefef4-ff90-4aab-85a5-eecbea26b889)
另外
ESP32-S3 上不支持int8 修改为了int8_t

**Comment by StarCompute** [comment]
谢谢，乱码的问题你试试最新代码，不要使用release版本。 同时建议使用项目中的那个字库。 都建议更新到最新。
int8这个刚刚更新，在esp8266和esp32dev下都编译通过了，s3的问题不大。
这几天人在外地，手里没有任何硬件，无法测试见谅。

**Comment by StarCompute** [comment]
问题还存在吗？
