### ISSUE TITLE
src/xfont 中，GetPixDatasFromLib(String displayStr)函数异常

### ISSUE THREAD

**Issue by WuliAPO** [StarCompute/tftziku#9]
背景：没有使用Arduino_GFX_Library库，只用了GetPixDatasFromLib函数来获取字符的二进制编码，以显示在墨水屏上。
描述：当displayStr参数为中文汉字时，无异常；当displayStr为ASCII字符时，无法获得正常的二进制编码。
如图，当显示“一二三123abc”时，会变成“一二三氘氙氚朕脒豚”
![微信图片_20240621154014](https://github.com/StarCompute/tftziku/assets/38987025/12cb6e89-2b52-4508-b1de-8b4054f5cbe0)

所用的字库是font/x_simfang.ttf_18_b64.font，其他字库文件没测试，但应该也是这样

**Comment by StarCompute** [comment]
见谅这么迟回复你，今天一天在路上
你使用的代码和字库是最新版本吗？
之前的是有这个问题。
不过我明天试试今天是不行了。

**Comment by StarCompute** [comment]
顺便请问一下，这个方法是有控制台输出的，请问输出正常吗？

**Comment by WuliAPO** [comment]
1、xfont 代码使用的是20240618版本，字库自己重新做了x_simfang.ttf_24_b64.font文件。
    其中，函数String getPixBinStrFromString(String strUnicode) 
            ...................
            char * chrFind=strstr(chrAllUnicodes,_str.c_str());
            int p =chrFind-strAllUnicodes.c_str();//p所得结果不对
            ....................
    例如‘1’被编码后是u0031，传入参数strUnicode为0031正常。搜索得到的结果p位置为31181，但手动查询，该位置的编码似乎是u6c18，为汉字‘氘’。
    尝试直接打印strAllUnicodes[p~p+4]，得到是u0031，又是正常的。

2、同时发现，倘若尝试直接显示‘氘’，此时p搜不到，结果是乱码（是不是在从flash读取strAllUnicodes的时候有问题？我是esp8266）

3、我也是在出差，今天发烧。注意身体

**Comment by StarCompute** [comment]
独立从字库获取像素的方法是GetPixDatasFromLib在Main文件中
  String _pixDatas=_xFont->GetPixDatasFromLib("1");
  int lenPixDatas=_pixDatas.length();
  for(int i=0;i<lenPixDatas;i++){
    if(i%18==0)Serial.println("");
    if(_pixDatas[i]=='1')Serial.print(_pixDatas[i]);
    else {
      Serial.print(" ");
    }
  }
上面的代码刚刚测试了一个中文和一个数字没有问题。
正常在控制台是可以看到类似下面的输出：



    1
   11
    1
    1
    1
    1
    1
    1
    1
    1
    1
   111

需要注意上面中的18需要被替换成相应的字号，你如果显示18是不需要任何替换的。
测试的条件是 x_simfang.ttf_18_b64.font
建议你重新复核一遍字库文件，或者使用我提供的字库文件。
如果还是不行建议删除你所有代码，下载最新，不一定要release版本。
unicode不匹配的问题，前几天按理说已经修正过了。涉及到了一些地方的处理不对。
如果还有问题尽快告知我

谢谢

**Comment by StarCompute** [comment]
独立从字库获取像素的方法是GetPixDatasFromLib在Main文件中
  String _pixDatas=_xFont->GetPixDatasFromLib("1");
  int lenPixDatas=_pixDatas.length();
  for(int i=0;i<lenPixDatas;i++){
    if(i%18==0)Serial.println("");
    if(_pixDatas[i]=='1')Serial.print(_pixDatas[i]);
    else {
      Serial.print(" ");
    }
  }
上面的代码刚刚测试了一个中文和一个数字没有问题。
正常在控制台是可以看到类似下面的输出：



    1
   11
    1
    1
    1
    1
    1
    1
    1
    1
    1
   111

需要注意上面中的18需要被替换成相应的字号，你如果显示18是不需要任何替换的。
测试的条件是 x_simfang.ttf_18_b64.font
建议你重新复核一遍字库文件，或者使用我提供的字库文件。
如果还是不行建议删除你所有代码，下载最新，不一定要release版本。
unicode不匹配的问题，前几天按理说已经修正过了。涉及到了一些地方的处理不对。
如果还有问题尽快告知我

谢谢

**Comment by StarCompute** [comment]
独立从字库获取像素的方法是GetPixDatasFromLib在Main文件中
  String _pixDatas=_xFont->GetPixDatasFromLib("1");
  int lenPixDatas=_pixDatas.length();
  for(int i=0;i<lenPixDatas;i++){
    if(i%18==0)Serial.println("");
    if(_pixDatas[i]=='1')Serial.print(_pixDatas[i]);
    else {
      Serial.print(" ");
    }
  }
上面的代码刚刚测试了一个中文和一个数字没有问题。
正常在控制台是可以看到类似下面的输出：



    1
   11
    1
    1
    1
    1
    1
    1
    1
    1
    1
   111

需要注意上面中的18需要被替换成相应的字号，你如果显示18是不需要任何替换的。
测试的条件是 x_simfang.ttf_18_b64.font
建议你重新复核一遍字库文件，或者使用我提供的字库文件。
如果还是不行建议删除你所有代码，下载最新，不一定要release版本。
unicode不匹配的问题，前几天按理说已经修正过了。涉及到了一些地方的处理不对。
如果还有问题尽快告知我

谢谢

**Comment by StarCompute** [comment]
补充说明：
使用x_simfang.ttf_24_b64.font 字库，
使用   String _pixDatas=_xFont->GetPixDatasFromLib("1"); 
传入是 0031,返回的P是P: 37325 ，
返回的像素数据解码后正常如下：

`
![微信截图_20240622165416](https://github.com/StarCompute/tftziku/assets/37955461/95b63337-4dbc-46e3-b105-2e639900d945)

我的结论是： 你使用的字库不匹配，请更新到最新。提醒注意，getxxx.py我最近也是更新了的。
